### ISSUE TITLE
cannot scroll down pull_request preview

### ISSUE THREAD

**Issue by traysh** [nvim-telescope/telescope-github.nvim#15]
should it work?

**Comment by windwp** [comment]
yes the default key is ctrl-d and ctrl-u

**Comment by traysh** [comment]
It does nothing for me. Maybe because of [my fix](https://github.com/nvim-telescope/telescope-github.nvim/pull/16)?

**Comment by Conni2461** [comment]
What is your `LESS` env output. I think if `-X` is set it should not work because that disables termcap which is used to send the commands to less.

(ads) You guys can also switch to buffer previewer. :) (ads)

**Comment by traysh** [comment]
```
env | grep LESS
LESS_TERMCAP_mb=
LESS_TERMCAP_md=
LESS_TERMCAP_me=
LESS_TERMCAP_se=
LESS_TERMCAP_so=
LESS_TERMCAP_ue=
LESS_TERMCAP_us=
```

I thought I was using the buffer previewer already, I did try to. Is there a way to check if it is being used?

**Comment by Conni2461** [comment]
windwp needs to implement them. Its not so easy here that he can just switch. But he can take i look what i am doing here: https://github.com/nvim-telescope/telescope.nvim/blob/1c5e42a6a5a6d29be8fbf8dcefb0d8da535eac9a/lua/telescope/previewers/buffer_previewer.lua#L508-L523 i think that should be similar to `gh_pr_preview`. 

I have no idea what the other thing does right now :rofl:

**Comment by traysh** [comment]
nice, thank you very much
