### ISSUE TITLE
`gh run` requires  a gh version ≤ 1.10.3

### ISSUE THREAD

**Issue by jacobfoard** [nvim-telescope/telescope-github.nvim#22]
[This line](https://github.com/nvim-telescope/telescope-github.nvim/blob/master/lua/telescope/_extensions/gh_make_entry.lua#L58) assumes the last entry in the table will be the id, but [gh 1.11.0](https://github.com/cli/cli/releases/tag/v1.11.0) added in the `elapsed` and `age` columns at the end.

Unfortunately, the columns between 1.10.3 and newer versions don't align, so the index would need to change depending on the version. 

I'm not sure what level of backwards compatibility this project hopes to maintain, so I figured I'd open an issue before submitting a patch that would require a new minimum version.

**Comment by windwp** [comment]
yes PR is welcome I only use gh pr so i am not check gh run
