### ISSUE TITLE
commands are not working

### ISSUE THREAD

**Issue by lalitmee** [nvim-telescope/telescope-github.nvim#24]
Somehow, I am not able to get this plugin to work. The day I installed it first time till today I get some errors.

Like:

```
E5108: Error executing lua .../packer/start/plenary.nvim/lua/plenary/window/border.lua:61: bad argument #1 to 'rep' (string expected, got table)
```

![image](https://user-images.githubusercontent.com/10762218/128215392-e0a22352-5c19-44e9-8c08-efc366f8e507.png)

This happens to every command either `Telescope gh issues` or `Telescope gh pull_request`. Can someone help me?

- **neovim version**
```
  NVIM v0.6.0-dev+104-g93443d59a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/lalitmee/data/Github/neovim/build/config -I/home/lalitmee/data/Github/neovim/src -I/home/lalitmee/data/Github/neovim/.deps/usr/include -I/usr/include -I/home/lalitmee/data/Github/neovim/build/src/nvim/auto -I/home/lalitmee/data/Github/neovim/build/include
Compiled by lalitmee@pop-os

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

- **environment**: PopOs (Ubuntu 20.04), 
- **terminal**: Kitty

**Comment by windwp** [comment]
what  is your version of gh cli?

i test with gh 1.13.1 working

**Comment by lalitmee** [comment]
I am using the latest version of `gh`

![image](https://user-images.githubusercontent.com/10762218/128661791-a30fa9e8-cc02-42ee-986c-9d5ba314d300.png)

**Comment by windwp** [comment]
sorry i don't know a problem i try v 1.14.0  and it working
that extenstion only read text from gh cli then it should working if gh command working .

**Comment by sbulav** [comment]
I don't think that this issue is still relevant.
If you think it's still actual, please open a new issue filling a new issue template.
