### ISSUE TITLE
Issue assignee option not working

### ISSUE THREAD

**Issue by jasonwoodland** [nvim-telescope/telescope-github.nvim#29]
I think filtering by assignee option should be `assignee`, not `assigner` here:
https://github.com/nvim-telescope/telescope-github.nvim/blob/master/lua/telescope/_extensions/gh_builtin.lua#L21

**Comment by sbulav** [comment]
Fixed in https://github.com/nvim-telescope/telescope-github.nvim/commit/abe424a49a5d3ba8532d4c245611874626795f24
