### ISSUE TITLE
Further plugin development

### ISSUE THREAD

**Issue by sbulav** [nvim-telescope/telescope-github.nvim#32]
Hi @windwp .
I really like this plugin and I use it in my daily activities.
However, as I see you're taking a break from supporting `telescope-github.nvim`. 
While this is totally fine, the plugin starts falling behind the CLI client and missing a lot of cool features.

Can you please share your plans for supporting this plugin?

p.s. I've implemented a few features in [my fork](https://github.com/sbulav/telescope-github.nvim). Let me know if you're interested in contributing them back.

**Comment by windwp** [comment]
hi @sbulav  
if you want i can ask @Conni2461  to make you have a permission to merge.

**Comment by sbulav** [comment]
OK, if you're fine with me taking care of it.
Not sure how much time I could spend on it, but I could at least do some PR reviews.

Hope you'll have more time/interest to contribute more to this plugin.

**Comment by Conni2461** [comment]
done

**Comment by sbulav** [comment]
Thanks! I'll dig into it after the public holidays.
