### ISSUE TITLE
Can't use option params in gist

### ISSUE THREAD

**Issue by deryrahman** [nvim-telescope/telescope-github.nvim#36]
Just a quick question. I tried to call telescope gist with option filter `public` but it's not working, it didn't show any gists. Here's the command I used.

```
:lua require('telescope').extensions.gh.gist({public=true})
```

Without options, it's completely working. But when I add `public=true` as options, it's not working. Am I missed something?

**Comment by sbulav** [comment]
No, this is a bug.

Running command:
```lua
:lua require('telescope').extensions.gh.gist({public=true})
```
Results in following cmd table:
```
{ "gh", "gist", "list", "--public", " " }
```

For some reason, with last empty `" "` argument this command is not handled properly via underlying function  [utils.get_os_command_output](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/utils.lua#L409)
