### ISSUE TITLE
Some feedback is needed while waiting for fetching stuff

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope-github.nvim#5]
There are a need for some feedback while fetching stuff so the user now something has been done

**Comment by windwp** [comment]
What feedback do you expect?

**Comment by tami5** [comment]
something simple like printing to command line `fetching from github.com ......`

**Comment by windwp** [comment]
it is easy to add a message in command line but I think it is not good option
after you run a command it display a floating telescope window and it make us focus on that window
then display a message in command line is not necessary

I just check and telescope don't have a function to display message on telescope window when execute an async request like this

**Comment by tami5** [comment]
hmmmm yah, I see what u mean, but still after the telescope window open there some bit of time where you look at an empty screen. Not sure as telescope window might enough indicator
