### ISSUE TITLE
change to use telescope export

### ISSUE THREAD

**Issue by windwp** [nvim-telescope/telescope-github.nvim#8]
@Conni2461

Currently we use `:Telescope gh_issues` for run command it is a nice command and easy to use even without mapping because it have autocomplete

if i use that export i need run `:Telescope ghcli gh_issues` or `:Telescope ghcli issuses` and the second path doesn't have autocomplete. It only complete ghcli word.

**Comment by Conni2461** [comment]
The second part will get completion with https://github.com/nvim-telescope/telescope.nvim/pull/398 not perfect but completion. 
You should be able to rename your `ghcli.lua` to `gh.lua` and then users can do `:Telescope gh issues`

I just don't think we should promote any bad practices in an "official" telescope extension. People will come by and look at the code of other extensions to get an understanding how to write their own extension.

**Comment by windwp** [comment]
I update it and i will merge after telescope support full autocomplete on extensions

**Comment by Conni2461** [comment]
Thank you :)
